### PR TITLE
Support for container width/height

### PR DESCRIPTION
**Pull request by TonyLianLong**
I'm able to make plotting work but I still cannot make thumbnail work with "width": "container". I suspect it's a CORS issue. However, it seems the spec I mentioned in https://github.com/julia-vscode/plotgallery/issues/12 does not actually contain external images, but external data (which is not supposed to cause any issue). In this situation, the PR still remains WIP.

### CODE REVIEW

**Comment by davidanthoff** [comment]
Can you try it with a plot that embeds the data?

**Comment by TonyLianLong** [comment]
It works with embedded data.

I used this example:
```{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "width": "container",
  "height": 250,
  "data": {"values": [
   {
      "Name":"chevrolet chevelle malibu",
      "Miles_per_Gallon":18,
      "Cylinders":8,
      "Displacement":307,
      "Horsepower":130,
      "Weight_in_lbs":3504,
      "Acceleration":12,
      "Year":"1970-01-01",
      "Origin":"USA"
   },{
      "Name":"chevrolet chevelle malibu",
      "Miles_per_Gallon":18,
      "Cylinders":8,
      "Displacement":307,
      "Horsepower":130,
      "Weight_in_lbs":3504,
      "Acceleration":12,
      "Year":"1970-01-01",
      "Origin":"Japan"
   },{
      "Name":"chevrolet chevelle malibu",
      "Miles_per_Gallon":18,
      "Cylinders":8,
      "Displacement":307,
      "Horsepower":130,
      "Weight_in_lbs":3504,
      "Acceleration":12,
      "Year":"1970-01-01",
      "Origin":"USA"
   }]},
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "Origin",
      "type": "nominal"
    },
    "y": {
      "aggregate": "count",
      "type": "quantitative"
    }
  }
}
```

Both the main plot and the thumbnail work:

**Comment by TonyLianLong** [comment]
Since the issue with thumbnail and external data is not directly related to this PR, I renamed this pull request so that it's no longer WIP.

**Comment by TonyLianLong** [comment]
To fix https://github.com/queryverse/ElectronDisplay.jl/issues/47, I set `width` and `height` of Plot to only 90% and add a margin of 5%.

**Comment by davidanthoff** [comment]
Great!

**Pull request merged**
